### ISSUE TITLE
Cannot build on macOS

### ISSUE THREAD

**Issue by antoineqian** [EQMG/Acid#132]
**Describe the bug**
Unable to build on macOs 12.5.1

**To Reproduce**
At the step:
```
xcodebuild -quiet -target Acid -configuration Release
```

**Expected behaviour**
compiles correctly

**Screenshots**

**Hardware:**
 - Device: intel core i9
 - OS: macOs 12.5.1

**Additional context**
I get the error
```
Acid/Sources/Audio/Wave/WaveSoundBuffer.cpp:4:10: fatal error:
      'OpenAL/al.h' file not found
#include <OpenAL/al.h>
         ^~~~~~~~~~~~~
/Users/antoineqian/c++/Acid/Sources/Audio/Wave/WaveSoundBuffer.cpp:4:10: note:
      did not find header 'al.h' in framework 'OpenAL' (loaded from '/Library/Frameworks')
```
I have installed openal-soft correctly

<img width="824" alt="image" src="https://user-images.githubusercontent.com/33892931/195191327-da658795-87a0-46c3-9272-b2b82daad006.png">

**Comment by olivia-banks** [comment]
Try uninstalling via vcpkg and compiling from Macports or from source, and see if that works. That worked for me.
